name: geo_ligtmeter
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  light: ^2.1.0
  flutter_map: ^0.14.0
  latlng: ^0.1.0
  location: ^4.3.0
  latlong2: ^0.8.1
  provider: ^6.0.2
  # sensors_plus: ^1.3.0
  fl_chart: ^0.46.0
  csv: ^5.0.1
  path_provider: ^2.0.9
  random_string: ^2.3.1
  file_picker: ^4.5.1
  flutter_svg: ^1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  flutter_launcher_icons: "^0.9.0"

flutter_icons:
  image_path: "assets/wireless_headset.png" 
  android: true
  ios: true
  
flutter:
  uses-material-design: true
